variables:
    blender:
        windows: c:/temp/blender.exe
        linux: /opt/myblenderbuild/blender
        darwin: /opt/myblenderbuild/blender

path_replacement:
    blender:
        windows: r:/
        linux: /render
        darwin: /Volume/render
